# Generated by Django 3.2.7 on 2021-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Auteur', 'Auteur'), ('Contributeur', 'Contributeur'), ('Responsable', 'Responsable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('A faire', 'A faire'), ('En cours', 'En cours'), ('Termine', 'Terminé')], max_length=50, verbose_name='status'),
        ),
    ]
