# Generated by Django 3.2.7 on 2021-10-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20211013_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
